/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package StudentInformation;

import javax.swing.JOptionPane;
import StudentServices.StudentService;
import java.io.IOException;

/**
 *
 * @author user
 */
public class StudentInformationFrame extends javax.swing.JInternalFrame {

    StudentTableModel model = new StudentTableModel();
    

    /**
     * Creates new form StudentInformationFrame
     */
    public StudentInformationFrame() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBtnGroup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dateOfBirth = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        femaleBtnRD = new javax.swing.JRadioButton();
        maleBtnRD = new javax.swing.JRadioButton();
        addStudentBtn = new javax.swing.JButton();
        majorComboBox = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("First Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 17, -1, -1));

        firstName.setText("s");
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        getContentPane().add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 13, 356, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 54, -1, -1));

        lastName.setText("s");
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        getContentPane().add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 356, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 102, -1, -1));

        email.setText("s");
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 98, 356, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Phone Number:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 151, -1, -1));

        phoneNumber.setText("s");
        phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberActionPerformed(evt);
            }
        });
        getContentPane().add(phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 141, 356, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Major:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 191, -1, -1));
        getContentPane().add(dateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 234, 160, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Date of Birth:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 236, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Gender:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 273, -1, -1));

        genderBtnGroup.add(femaleBtnRD);
        femaleBtnRD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        femaleBtnRD.setText("Female");
        femaleBtnRD.setActionCommand("female");
        femaleBtnRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleBtnRDActionPerformed(evt);
            }
        });
        getContentPane().add(femaleBtnRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 265, -1, 37));

        genderBtnGroup.add(maleBtnRD);
        maleBtnRD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        maleBtnRD.setText("Male");
        maleBtnRD.setActionCommand("male");
        maleBtnRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleBtnRDActionPerformed(evt);
            }
        });
        getContentPane().add(maleBtnRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 265, 65, 37));

        addStudentBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addStudentBtn.setText("Add Student");
        addStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addStudentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 340, -1, -1));

        majorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Engineering", "IT", "Data Science" }));
        getContentPane().add(majorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 189, 356, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberActionPerformed

    private void femaleBtnRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleBtnRDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleBtnRDActionPerformed

    private void maleBtnRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleBtnRDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleBtnRDActionPerformed

    private void addStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBtnActionPerformed
        if (firstName.getText().equals("") || lastName.getText().equals("") || email.getText().equals("") || phoneNumber.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "All Fields are required!", "Message", JOptionPane.ERROR_MESSAGE);
        } else {
//            System.out.println(majorComboBox.getSelectedItem().toString());
            StudentService service = new StudentService();          
            Student student = new Student(
                    firstName.getText(), 
                    lastName.getText(), 
                    email.getText(), 
                    phoneNumber.getText(), 
                    majorComboBox.getSelectedItem().toString(), 
                    dateOfBirth.getDate(), 
                    genderBtnGroup.getSelection().getActionCommand());
            System.out.println(genderBtnGroup.getSelection().getActionCommand());
            try {
                service.save(student);
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
            model.students = service.getAll();
            model.fireTableDataChanged();
            firstName.setText("");
            lastName.setText("");
            email.setText("");
            phoneNumber.setText("");
            
        }

    }//GEN-LAST:event_addStudentBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudentBtn;
    private com.toedter.calendar.JDateChooser dateOfBirth;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton femaleBtnRD;
    private javax.swing.JTextField firstName;
    private javax.swing.ButtonGroup genderBtnGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lastName;
    private javax.swing.JComboBox<String> majorComboBox;
    private javax.swing.JRadioButton maleBtnRD;
    private javax.swing.JTextField phoneNumber;
    // End of variables declaration//GEN-END:variables
}
