/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.studentmanagementsystem;

import java.awt.Color;

/**
 *
 * @author ALE
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editRecordsPanel = new javax.swing.JPanel();
        editRecords = new javax.swing.JLabel();
        studentInformationPanel = new javax.swing.JPanel();
        studentInformation = new javax.swing.JLabel();
        logoutAdminPagePanel = new javax.swing.JPanel();
        logoutAdminPage = new javax.swing.JLabel();
        teacherInformationPanel = new javax.swing.JPanel();
        teacherInformation = new javax.swing.JLabel();
        teacherInformationPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Page");

        editRecordsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editRecordsPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editRecordsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editRecordsPanelMouseExited(evt);
            }
        });

        editRecords.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        editRecords.setText("Edit Records");
        editRecords.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editRecordsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editRecordsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editRecordsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout editRecordsPanelLayout = new javax.swing.GroupLayout(editRecordsPanel);
        editRecordsPanel.setLayout(editRecordsPanelLayout);
        editRecordsPanelLayout.setHorizontalGroup(
            editRecordsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editRecordsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );
        editRecordsPanelLayout.setVerticalGroup(
            editRecordsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editRecordsPanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(editRecords)
                .addGap(9, 9, 9))
        );

        studentInformationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentInformationPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentInformationPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentInformationPanelMouseExited(evt);
            }
        });

        studentInformation.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        studentInformation.setText("Student Information");
        studentInformation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentInformationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentInformationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentInformationMouseExited(evt);
            }
        });

        javax.swing.GroupLayout studentInformationPanelLayout = new javax.swing.GroupLayout(studentInformationPanel);
        studentInformationPanel.setLayout(studentInformationPanelLayout);
        studentInformationPanelLayout.setHorizontalGroup(
            studentInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentInformation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentInformationPanelLayout.setVerticalGroup(
            studentInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentInformationPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(studentInformation)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        logoutAdminPagePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutAdminPagePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutAdminPagePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutAdminPagePanelMouseExited(evt);
            }
        });

        logoutAdminPage.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        logoutAdminPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutAdminPage.setText("Logout");
        logoutAdminPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutAdminPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutAdminPageMouseExited(evt);
            }
        });

        javax.swing.GroupLayout logoutAdminPagePanelLayout = new javax.swing.GroupLayout(logoutAdminPagePanel);
        logoutAdminPagePanel.setLayout(logoutAdminPagePanelLayout);
        logoutAdminPagePanelLayout.setHorizontalGroup(
            logoutAdminPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutAdminPagePanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(logoutAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoutAdminPagePanelLayout.setVerticalGroup(
            logoutAdminPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutAdminPagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutAdminPage, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        teacherInformationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherInformationPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                teacherInformationPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                teacherInformationPanelMouseExited(evt);
            }
        });

        teacherInformation.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        teacherInformation.setText("Teacher Information");
        teacherInformation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        teacherInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherInformationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                teacherInformationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                teacherInformationMouseExited(evt);
            }
        });

        javax.swing.GroupLayout teacherInformationPanelLayout = new javax.swing.GroupLayout(teacherInformationPanel);
        teacherInformationPanel.setLayout(teacherInformationPanelLayout);
        teacherInformationPanelLayout.setHorizontalGroup(
            teacherInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacherInformation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        teacherInformationPanelLayout.setVerticalGroup(
            teacherInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherInformationPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(teacherInformation)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editRecordsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutAdminPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teacherInformationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(editRecordsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutAdminPagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "ID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        teacherInformationPane.addTab("Edit Records", jScrollPane1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Courses Taking", "Email"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        teacherInformationPane.addTab("Student Information", jScrollPane3);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Course Teaching", "Email"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        teacherInformationPane.addTab("Teacher Information", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherInformationPane, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(teacherInformationPane, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editRecordsMouseClicked
        // TODO add your handling code here:
        teacherInformationPane.setSelectedIndex(0);
    }//GEN-LAST:event_editRecordsMouseClicked

    private void editRecordsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editRecordsMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(158, 152, 152);
        editRecords.setBackground(clr);
    }//GEN-LAST:event_editRecordsMouseEntered

    private void editRecordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editRecordsMouseExited
        // TODO add your handling code here:
        Color clr = new Color(214,217,223);
        editRecords.setBackground(clr);
    }//GEN-LAST:event_editRecordsMouseExited

    private void editRecordsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editRecordsPanelMouseClicked
        // TODO add your handling code here:
        teacherInformationPane.setSelectedIndex(0);
    }//GEN-LAST:event_editRecordsPanelMouseClicked

    private void editRecordsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editRecordsPanelMouseEntered
        Color clr = new Color(158, 152, 152);
        editRecordsPanel.setBackground(clr);
    }//GEN-LAST:event_editRecordsPanelMouseEntered

    private void editRecordsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editRecordsPanelMouseExited
        // TODO add your handling code here:
        Color clr = new Color(214,217,223);
        editRecordsPanel.setBackground(clr);

    }//GEN-LAST:event_editRecordsPanelMouseExited

    private void studentInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentInformationMouseClicked
        // TODO add your handling code here:
        teacherInformationPane.setSelectedIndex(1);
    }//GEN-LAST:event_studentInformationMouseClicked

    private void studentInformationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentInformationMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_studentInformationMouseEntered

    private void studentInformationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentInformationMouseExited
        // TODO add your handling code here:
        Color clr = new Color(214,217,223);
        studentInformation.setBackground(clr);
    }//GEN-LAST:event_studentInformationMouseExited

    private void studentInformationPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentInformationPanelMouseClicked
        // TODO add your handling code here:
        teacherInformationPane.setSelectedIndex(1);
    }//GEN-LAST:event_studentInformationPanelMouseClicked

    private void studentInformationPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentInformationPanelMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(158, 152, 152);
        studentInformationPanel.setBackground(clr);
    }//GEN-LAST:event_studentInformationPanelMouseEntered

    private void studentInformationPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentInformationPanelMouseExited
        // TODO add your handling code here:\
        Color clr = new Color(214,217,223);
        studentInformationPanel.setBackground(clr);
    }//GEN-LAST:event_studentInformationPanelMouseExited

    private void logoutAdminPageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutAdminPageMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(158,152,152);
        logoutAdminPage.setBackground(clr);
    }//GEN-LAST:event_logoutAdminPageMouseEntered

    private void logoutAdminPageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutAdminPageMouseExited
        // TODO add your handling code here:
        Color clr = new Color(214,217,223);
        logoutAdminPage.setBackground(clr);
    }//GEN-LAST:event_logoutAdminPageMouseExited

    private void logoutAdminPagePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutAdminPagePanelMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(158,152,152);
        logoutAdminPagePanel.setBackground(clr);
    }//GEN-LAST:event_logoutAdminPagePanelMouseEntered

    private void logoutAdminPagePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutAdminPagePanelMouseExited
        // TODO add your handling code here:
        Color clr = new Color(214,217,223);
        logoutAdminPagePanel.setBackground(clr);
    }//GEN-LAST:event_logoutAdminPagePanelMouseExited

    private void teacherInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherInformationMouseClicked
        // TODO add your handling code here:
        teacherInformationPane.setSelectedIndex(2);
    }//GEN-LAST:event_teacherInformationMouseClicked

    private void teacherInformationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherInformationMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherInformationMouseEntered

    private void teacherInformationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherInformationMouseExited
        // TODO add your handling code here:
        Color clr = new Color(214,217,223);
        teacherInformation.setBackground(clr);
    }//GEN-LAST:event_teacherInformationMouseExited

    private void teacherInformationPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherInformationPanelMouseClicked
        // TODO add your handling code here:
        teacherInformationPane.setSelectedIndex(2);
    }//GEN-LAST:event_teacherInformationPanelMouseClicked

    private void teacherInformationPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherInformationPanelMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(158,152,152);
        teacherInformationPanel.setBackground(clr);
    }//GEN-LAST:event_teacherInformationPanelMouseEntered

    private void teacherInformationPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherInformationPanelMouseExited
        // TODO add your handling code here:
        Color clr = new Color(214,217,223);
        teacherInformationPanel.setBackground(clr);
    }//GEN-LAST:event_teacherInformationPanelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel editRecords;
    private javax.swing.JPanel editRecordsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel logoutAdminPage;
    private javax.swing.JPanel logoutAdminPagePanel;
    private javax.swing.JLabel studentInformation;
    private javax.swing.JPanel studentInformationPanel;
    private javax.swing.JLabel teacherInformation;
    private javax.swing.JTabbedPane teacherInformationPane;
    private javax.swing.JPanel teacherInformationPanel;
    // End of variables declaration//GEN-END:variables
}
