/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI_and_TableModels;

import model_classes.*;
import Services.*;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import Design.*;

/**
 *
 * @author nonyx
 */
public class StudentInformationFrame extends javax.swing.JInternalFrame {

    StudentTableModel model;
    public static String foreign_name;
    public static int foreign_id;

    //major list
    ArrayList<String> majorList = new ArrayList<String>();
    //gender list
    ArrayList<String> genderList = new ArrayList<String>();

    /**
     * Creates new form StudentInformationFrame
     */
    public StudentInformationFrame() {
        model = new StudentTableModel();
        StudentService service = new StudentService();
        model.students = service.getAll();

        initComponents();
        //adding fields to majorList
        majorList.add("Software Engineering");
        majorList.add("Computer Science");
        //adding fields to genderList
        genderList.add("Male");
        genderList.add("Female");
        for (String major : majorList) {
            majorComboBox.addItem(major);
        }
        for (String gender : genderList) {
            genderComboBox.addItem(gender);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        idSpinner = new javax.swing.JSpinner();
        editButton = new ButtonRound();
        jPanel1 = new javax.swing.JPanel();
        dateField = new com.toedter.calendar.JDateChooser();
        firstNameField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addButton = new ButtonRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        majorComboBox = new javax.swing.JComboBox<>();
        emailField = new javax.swing.JTextField();
        phoneNumberField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(216, 216, 216));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Student Registration Form");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(model);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 348, 1140, 270));

        jLabel2.setText("Enter ID to edit transcript");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 106, -1, -1));
        getContentPane().add(idSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 134, 80, -1));

        ButtonRound editButton = new ButtonRound();
        editButton.setRadius(40);
        editButton.setBackground(new java.awt.Color(63, 63, 65));
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText(" Edit Transcript");
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
        });
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 172, -1, 40));

        jPanel1.setBackground(new java.awt.Color(216, 216, 216));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 205, -1));
        jPanel1.add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 210, -1));

        jLabel8.setText("First Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        ButtonRound addButton = new ButtonRound();
        addButton.setRadius(40);
        addButton.setBackground(new java.awt.Color(63, 63, 65));
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add Student");
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 298, 120, 40));

        jLabel1.setText("Last Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel3.setText("Phone");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jLabel7.setText("BirthDate");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        jLabel5.setText("Major");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        jLabel6.setText("Gender");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        jPanel1.add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 90, -1));

        jPanel1.add(majorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 210, -1));
        jPanel1.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 210, -1));
        jPanel1.add(phoneNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 210, -1));
        jPanel1.add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 1190, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (firstNameField.getText().equals("") || lastNameField.getText().equals("") || phoneNumberField.getText().equals("") || emailField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "All Fields are required!");
        } else {
            StudentService service = new StudentService();

//            st.setDateOfBirth(dateField.getDate().toString());
            String name = firstNameField.getText() + " " + lastNameField.getText();
            Student student = new Student(name, phoneNumberField.getText(), dateField.getDate(), emailField.getText(), (String) majorComboBox.getSelectedItem(), (String) genderComboBox.getSelectedItem());
            student.setFirstName(firstNameField.getText());
            student.setLastName(lastNameField.getText());

            try {
                service.save(student);
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
            model.students = service.getAll();
            model.fireTableDataChanged();
            firstNameField.setText("");
            lastNameField.setText("");
            emailField.setText("");
            dateField.setDateFormatString("");
            phoneNumberField.setText("");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if ((int) idSpinner.getValue() > model.students.size() || (int) idSpinner.getValue() < 0 || (int) idSpinner.getValue() == 0) {
            JOptionPane.showMessageDialog(this, "No student with id " + (int) idSpinner.getValue());
        } else {
            if ((int) idSpinner.getValue() > 0 && (int) idSpinner.getValue() <= model.students.size()) {
                foreign_name = model.students.get((int) idSpinner.getValue() - 1).getFullName();
                foreign_id = model.students.get((int) idSpinner.getValue() - 1).getID();
                JInternalFrame tf = new TranscriptFrame();
                tf.setVisible(true);
                getParent().add(tf);
                dispose();
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked

    }//GEN-LAST:event_editButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInformationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private com.toedter.calendar.JDateChooser dateField;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JSpinner idSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JComboBox<String> majorComboBox;
    private javax.swing.JTextField phoneNumberField;
    // End of variables declaration//GEN-END:variables
}
