/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Transcript;

import com.services.TranscriptService;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nonyx
 */
public class TranscriptFrame extends javax.swing.JInternalFrame {

    TranscriptTableModel model;
    StudentInformationFrame studentInformationFrame = new StudentInformationFrame();
    /**
     * Creates new form TranscriptFrame
     */
    ArrayList<String> courseTitle = new ArrayList<String>();

    public TranscriptFrame() {
        model = new TranscriptTableModel();
        TranscriptService service = new TranscriptService();
        model.transcripts = service.getAll();
        System.out.println(StudentInformationFrame.foreign_name);
        System.out.println(StudentInformationFrame.foreign_id);

        initComponents();

        studentNameField.setText(StudentInformationFrame.foreign_name);
        studentIDField.setText(Integer.toString(StudentInformationFrame.foreign_id));

        courseTitle.add("Introduction to Computer Systems");
        courseTitle.add("Fundementals of programmign");
        courseTitle.add("Discrete Mathematics");
        courseTitle.add("College English");
        courseTitle.add("Introduction to Logic & Critical Thinking");
        courseTitle.add("Geography of Ethiopia & the horn");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentNameField = new javax.swing.JTextField();
        studentIDField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        credithourField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lettergradeField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        gradepointField = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Student Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 115, -1, -1));

        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 149, -1, -1));

        studentNameField.setEditable(false);
        getContentPane().add(studentNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 109, 159, -1));

        studentIDField.setEditable(false);
        getContentPane().add(studentIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 143, 89, -1));

        jTable1.setModel(model);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 189, 770, 270));

        jLabel3.setText("Credit Hour");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 12, -1, -1));
        getContentPane().add(credithourField, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 6, 83, -1));

        jLabel4.setText("Letter Grade");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 46, -1, -1));
        getContentPane().add(lettergradeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 40, 83, -1));

        jLabel5.setText("Grade Point");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 86, -1, -1));
        getContentPane().add(gradepointField, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 80, 83, -1));

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(enterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 120, -1, -1));

        jPanel1.setBackground(new java.awt.Color(216, 216, 216));

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327)
                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(597, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(483, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(printButton))
                .addGap(139, 139, 139))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        if (credithourField.getText().equals("") && lettergradeField.getText().equals("") && gradepointField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Credit hour, Letter grade and Grade point are required");
        } else {
            TranscriptService service = new TranscriptService();
            Transcript transcript = new Transcript(courseTitle.get(model.transcripts.size()), Integer.parseInt(credithourField.getText()), lettergradeField.getText().charAt(0), Integer.parseInt(gradepointField.getText()));
            try {
                service.save(transcript);
            } catch (IOException ex) {
                //...
            }
            model.transcripts = service.getAll();
            model.fireTableDataChanged();
            credithourField.setText("");
            lettergradeField.setText("");
            gradepointField.setText("");
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        JInternalFrame sf = new StudentInformationFrame();
        sf.setVisible(true);
        getParent().add(sf);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    @SuppressWarnings("empty-statement")
    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose your file path");
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
               //I have added some file handling concept here. What do you say???
            try {
                FileWriter fw = new FileWriter(fileToSave);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(new TranscriptTableModel().getColumnNames());
                bw.newLine();
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    for (int j = 0; j < jTable1.getColumnCount(); j++) {
                        //write
                        bw.write(jTable1.getValueAt(i, j).toString() + ",");
                    }
                    bw.newLine();//record per line 
                }
                JOptionPane.showMessageDialog(this, "SUCCESSFULLY SAVED", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
                bw.close();
                fw.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "ERROR", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TranscriptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TranscriptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TranscriptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TranscriptFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TranscriptFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField credithourField;
    private javax.swing.JButton enterButton;
    private javax.swing.JTextField gradepointField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lettergradeField;
    private javax.swing.JButton printButton;
    private javax.swing.JTextField studentIDField;
    private javax.swing.JTextField studentNameField;
    // End of variables declaration//GEN-END:variables
}
