/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI_and_TableModels;

import Design.*;
import java.awt.Frame;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ALazar
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame(){
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentRegistrationFormBtn = new ButtonRound();
        transcriptInformationBtn = new ButtonRound();
        courseManagmentBtn = new ButtonRound();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentRegistrationFormBtn.setBackground(new java.awt.Color(63, 63, 65));
        studentRegistrationFormBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        studentRegistrationFormBtn.setForeground(new java.awt.Color(255, 255, 255));
        studentRegistrationFormBtn.setText("Student Registration Form");
        studentRegistrationFormBtn.setToolTipText("Click to register a student");
        studentRegistrationFormBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentRegistrationFormBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRegistrationFormBtnActionPerformed(evt);
            }
        });
        getContentPane().add(studentRegistrationFormBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 300, 60));

        transcriptInformationBtn.setBackground(new java.awt.Color(63, 63, 65));
        transcriptInformationBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        transcriptInformationBtn.setForeground(new java.awt.Color(255, 255, 255));
        transcriptInformationBtn.setText("Transcript Information");
        transcriptInformationBtn.setToolTipText("Click to edit and see Students Transcript Information");
        transcriptInformationBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transcriptInformationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transcriptInformationBtnActionPerformed(evt);
            }
        });
        getContentPane().add(transcriptInformationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 300, 60));

        courseManagmentBtn.setBackground(new java.awt.Color(63, 63, 65));
        courseManagmentBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        courseManagmentBtn.setForeground(new java.awt.Color(255, 255, 255));
        courseManagmentBtn.setText("Course Managment");
        courseManagmentBtn.setToolTipText("Click to add a student to a course.");
        courseManagmentBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        courseManagmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseManagmentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(courseManagmentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, 300, 60));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(63, 63, 65));
        jLabel4.setText("Welcome");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 220, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setText("Logout");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/studentRegistration.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transcript.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/course-management-5-512 (1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 200, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizeMac.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeMac.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        int a = JOptionPane.showConfirmDialog(this, "Do you want to logout?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            this.setVisible(false);
            new Login().setVisible(true);
        }

    }//GEN-LAST:event_jLabel5MouseClicked

    private void studentRegistrationFormBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRegistrationFormBtnActionPerformed
        this.setVisible(false);
        new StudentPanelFrame().setVisible(true);


    }//GEN-LAST:event_studentRegistrationFormBtnActionPerformed

    private void courseManagmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseManagmentBtnActionPerformed
        this.setVisible(false);
        new StudentPanelFrame().setVisible(true);
    }//GEN-LAST:event_courseManagmentBtnActionPerformed

    private void transcriptInformationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transcriptInformationBtnActionPerformed
        this.setVisible(false);
        new StudentPanelFrame().setVisible(true);
    }//GEN-LAST:event_transcriptInformationBtnActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton courseManagmentBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton studentRegistrationFormBtn;
    private javax.swing.JButton transcriptInformationBtn;
    // End of variables declaration//GEN-END:variables
}
