/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI_and_TableModels;

import model_classes.*;
import Services.*;
import javax.swing.JTable;
import Design.*;
import javax.swing.ListSelectionModel;

/**
 *
 * @author user
 */
public class StudentEnrolmentInternalFrame extends javax.swing.JInternalFrame {

    StudentEnrolmentTableModel model;
    private int studentId;
//    List<Enrolment> enrolments = new ArrayList<>();

    /**
     * Creates new form StudentEnrolmentInternalFrame
     *
     * @param id
     */
    public StudentEnrolmentInternalFrame(int id) {
        this.studentId = id;
        model = new StudentEnrolmentTableModel();
        StudentEnrolmentService service = new StudentEnrolmentService();
        model.enrolments = service.getEnrolmentList(studentId);
        model.courses = service.getCourseList();

        initComponents();

        studentName.setText(service.getStudent(studentId).toString());
        yearAndSemester.setText(service.getStudent(studentId).getYearAndSemester());

        enrolmentTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        enrolmentTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        enrolmentTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        enrolmentTable.getColumnModel().getColumn(2).setPreferredWidth(20);
        enrolmentTable.getColumnModel().getColumn(3).setPreferredWidth(20);
        enrolmentTable.getColumnModel().getColumn(4).setPreferredWidth(20);
        enrolmentTable.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);

    }

    public StudentEnrolmentInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enrolmentTable = new javax.swing.JTable();
        studentName = new javax.swing.JLabel();
        changeEnrolment = new ButtonRound();
        yearAndSemester = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 216, 216));
        setClosable(true);
        setIconifiable(true);
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setText("Student Course Enrolment");

        enrolmentTable.setModel(model);
        enrolmentTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(enrolmentTable);

        studentName.setText("Null");

        ButtonRound changeEnrolment = new ButtonRound();
        changeEnrolment.setRadius(40);
        changeEnrolment.setBackground(new java.awt.Color(63, 63, 65));
        changeEnrolment.setForeground(new java.awt.Color(255, 255, 255));
        changeEnrolment.setText("Change Enrollment Status");
        changeEnrolment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeEnrolment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeEnrolmentActionPerformed(evt);
            }
        });

        yearAndSemester.setText("Null");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yearAndSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changeEnrolment, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeEnrolment, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearAndSemester))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeEnrolmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeEnrolmentActionPerformed
        int row = enrolmentTable.getSelectedRow();
        Enrolment selectedEnrolment = model.matchedEnrolments.get(row);

        boolean newEnrolledValue = !(selectedEnrolment.isEnrolled());

        selectedEnrolment.setEnrolled(newEnrolledValue);

        StudentEnrolmentService service = new StudentEnrolmentService();
        service.updateEnrolment(selectedEnrolment, "enrolled", newEnrolledValue);

        model.fireTableDataChanged();
    }//GEN-LAST:event_changeEnrolmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeEnrolment;
    private javax.swing.JTable enrolmentTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel studentName;
    private javax.swing.JLabel yearAndSemester;
    // End of variables declaration//GEN-END:variables
}
